databases:
  - name: class_memories_db
    databaseName: class_memories
    user: class_memories
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: class-memories
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn class_memories.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: class_memories_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false
